version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:dev-v2-RC_11_28_22_04_01a"
    network_mode: host
    # restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      # Logging
      - VERBOSE=1
      - DEBUG=1
      # Oracle
      - CHAIN=solana
      # Solana
      - CLUSTER=${CLUSTER:-devnet}
      - RPC_URL=${RPC_URL:-https://api.devnet.solana.com}
      - ORACLE_KEY=${ORACLE_KEY}
      - HEARTBEAT_INTERVAL=60 # Seconds
      # Task Runner
      - TASK_RUNNER_SOLANA_RPC=${TASK_RUNNER_SOLANA_RPC:-https://api.mainnet-beta.solana.com}
secrets:
  PAYER_SECRETS:
    file: ${SOLANA_PAYER_SECRETS:-~/.config/solana/id.json}
