[package]
name = "switchboard-v2"
version = "0.1.17"
edition = "2021"
description = "A Rust library to interact with Switchboard V2 accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sbv2-solana/tree/main/libraries/rs"
license = "MIT"
documentation = "https://docs.rs/switchboard-v2/"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_v2"
doctest = false

[features]
default = ["cpi"]
no-entrypoint = []
cpi = ["no-entrypoint"]
## The devnet feature enables using the Switchboard Devnet Program ID instead of the Mainnet Program ID.
devnet = []

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
rust_decimal = "1.26.0"
solana-program = "1.14.9"
bytemuck = "1.7.2"
superslice = "1"
spl-token = "3.3.1"

# solana-program = "1.10"
# spl-token = "3.5"
# anchor-lang = { git = "https://github.com/coral-xyz/anchor.git", rev = "66e4295fe0d2cc2456055bea50e8d227492bdbad" }
# anchor-spl = { git = "https://github.com/coral-xyz/anchor.git", rev = "66e4295fe0d2cc2456055bea50e8d227492bdbad" }
